    version: "3"
    services:
      client:
        image: "lukasjvdm/rest-api-client"
        mem_limit: 128m
        hostname: client
      server:
        image: "lukasjvdm/rest-api-server"
        mem_limit: 128m
        hostname: api
        environment:
          - PGUSER=$PGUSER
          - PGHOST=$PGHOST
          - PGDATABASE=$PGDATABASE
          - PGPASSWORD=$PGPASSWORD
          - PGPORT=$PGPORT
      nginx:
        image: "lukasjvdm/rest-api-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
          - "80:80"